export interface Game {
  id: string;
  name: string;
  slug: string;
  description: string;
  longDescription: string;
  category: string[];
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Variable';
  players: string;
  thumbnail: string;
  featured: boolean;
  popular: boolean;
  isNew: boolean;
  tags: string[];
  controls: string;
  color: string;
  emoji: string;
}

export const games: Game[] = [
  {
    id: '1',
    name: 'Tic Tac Toe',
    slug: 'tic-tac-toe',
    description: 'Classic X and O game. Play against a friend or challenge the AI.',
    longDescription: 'The timeless classic — place X or O and get three in a row. Play against another player or test yourself against the AI with Easy, Medium, or Hard difficulty.',
    category: ['Classic', 'Board', 'Multiplayer'],
    difficulty: 'Easy',
    players: '1-2',
    thumbnail: '/images/tictactoe.svg',
    featured: true,
    popular: true,
    isNew: false,
    tags: ['classic', 'board', 'two-player', 'ai', 'strategy'],
    controls: 'Mouse / Touch',
    color: '#6366f1',
    emoji: '⭕',
  },
  {
    id: '2',
    name: 'Snake',
    slug: 'snake',
    description: 'Eat food, grow longer, don\'t hit the walls or yourself!',
    longDescription: 'Guide your snake to eat food and grow longer. Avoid crashing into walls or your own tail. How long can you survive?',
    category: ['Arcade', 'Classic', 'Skill'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/snake.svg',
    featured: true,
    popular: true,
    isNew: false,
    tags: ['snake', 'arcade', 'classic', 'keyboard', 'mobile'],
    controls: 'Arrow Keys / WASD / Swipe',
    color: '#22c55e',
    emoji: '🐍',
  },
  {
    id: '3',
    name: '2048',
    slug: '2048',
    description: 'Slide tiles and combine them to reach the 2048 tile.',
    longDescription: 'Slide numbered tiles on a 4×4 grid and combine matching numbers. Reach the 2048 tile to win — but can you go further?',
    category: ['Puzzle', 'Strategy'],
    difficulty: 'Medium',
    players: '1',
    thumbnail: '/images/2048.svg',
    featured: true,
    popular: true,
    isNew: false,
    tags: ['2048', 'puzzle', 'numbers', 'swipe', 'strategy'],
    controls: 'Arrow Keys / Swipe',
    color: '#f59e0b',
    emoji: '🔢',
  },
  {
    id: '4',
    name: 'Memory Card',
    slug: 'memory',
    description: 'Flip cards and find matching pairs. Test your memory!',
    longDescription: 'Flip over cards to find matching pairs. Choose from multiple themes and difficulty levels. The fewer moves you use, the better your score.',
    category: ['Puzzle', 'Casual'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/memory.svg',
    featured: false,
    popular: true,
    isNew: false,
    tags: ['memory', 'cards', 'matching', 'puzzle', 'casual'],
    controls: 'Mouse / Touch',
    color: '#ec4899',
    emoji: '🃏',
  },
  {
    id: '5',
    name: 'Minesweeper',
    slug: 'minesweeper',
    description: 'Reveal the grid without triggering hidden mines.',
    longDescription: 'Uncover safe cells while avoiding hidden mines. Use numbers to deduce mine locations and flag them. A classic logic puzzle.',
    category: ['Puzzle', 'Classic', 'Strategy'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/minesweeper.svg',
    featured: false,
    popular: true,
    isNew: false,
    tags: ['minesweeper', 'logic', 'puzzle', 'classic', 'mines'],
    controls: 'Mouse / Touch',
    color: '#ef4444',
    emoji: '💣',
  },
  {
    id: '6',
    name: 'Rock Paper Scissors',
    slug: 'rock-paper-scissors',
    description: 'The ultimate hand game. Can you beat the computer?',
    longDescription: 'Rock beats scissors, scissors beats paper, paper beats rock. Play best of 3 or best of 5 against the computer.',
    category: ['Casual', 'Classic'],
    difficulty: 'Easy',
    players: '1',
    thumbnail: '/images/rps.svg',
    featured: false,
    popular: false,
    isNew: false,
    tags: ['rock', 'paper', 'scissors', 'casual', 'quick'],
    controls: 'Mouse / Touch',
    color: '#8b5cf6',
    emoji: '✌️',
  },
  {
    id: '7',
    name: 'Connect Four',
    slug: 'connect-four',
    description: 'Drop discs and connect four in a row before your opponent.',
    longDescription: 'Drop colored discs into the grid. Be the first to connect four in a row — horizontally, vertically, or diagonally.',
    category: ['Board', 'Strategy', 'Multiplayer'],
    difficulty: 'Medium',
    players: '1-2',
    thumbnail: '/images/connectfour.svg',
    featured: false,
    popular: true,
    isNew: false,
    tags: ['connect four', 'board', 'strategy', 'two-player', 'ai'],
    controls: 'Mouse / Touch',
    color: '#f97316',
    emoji: '🔴',
  },
  {
    id: '8',
    name: 'Checkers',
    slug: 'checkers',
    description: 'Classic draughts game with legal moves, captures, and king pieces.',
    longDescription: 'Play the classic game of checkers. Jump over opponent pieces to capture them. Reach the far end to become a king. Eliminate all opponent pieces to win.',
    category: ['Board', 'Strategy', 'Classic'],
    difficulty: 'Medium',
    players: '1-2',
    thumbnail: '/images/checkers.svg',
    featured: false,
    popular: false,
    isNew: false,
    tags: ['checkers', 'draughts', 'board', 'strategy', 'classic'],
    controls: 'Mouse / Touch',
    color: '#d97706',
    emoji: '⚫',
  },
  {
    id: '9',
    name: 'Sudoku',
    slug: 'sudoku',
    description: 'Fill the 9×9 grid with digits 1–9. No repeats in any row, column, or box.',
    longDescription: 'Fill every row, column, and 3×3 box with the digits 1–9 without repeating. Choose your difficulty, use hints, and track your time.',
    category: ['Puzzle', 'Strategy'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/sudoku.svg',
    featured: true,
    popular: true,
    isNew: false,
    tags: ['sudoku', 'puzzle', 'numbers', 'logic', 'strategy'],
    controls: 'Mouse / Keyboard',
    color: '#0ea5e9',
    emoji: '🔢',
  },
  {
    id: '10',
    name: 'Flappy Rocket',
    slug: 'flappy-rocket',
    description: 'Tap to fly your rocket through gaps. How far can you go?',
    longDescription: 'Tap or click to make your rocket thrust upward. Navigate through gaps in obstacles. Each obstacle passed scores a point. Don\'t crash!',
    category: ['Arcade', 'Skill', 'Casual'],
    difficulty: 'Hard',
    players: '1',
    thumbnail: '/images/flappy.svg',
    featured: true,
    popular: true,
    isNew: true,
    tags: ['flappy', 'arcade', 'skill', 'tap', 'rocket'],
    controls: 'Click / Tap / Space',
    color: '#06b6d4',
    emoji: '🚀',
  },
  {
    id: '11',
    name: 'Breakout',
    slug: 'breakout',
    description: 'Break all the bricks with your ball and paddle.',
    longDescription: 'Control the paddle to bounce the ball and destroy all the bricks. Don\'t let the ball fall past your paddle. Multiple levels and increasing difficulty.',
    category: ['Arcade', 'Classic', 'Skill'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/breakout.svg',
    featured: false,
    popular: true,
    isNew: false,
    tags: ['breakout', 'arcade', 'ball', 'paddle', 'bricks', 'classic'],
    controls: 'Mouse / Touch / Arrow Keys',
    color: '#84cc16',
    emoji: '🧱',
  },
  {
    id: '12',
    name: 'Pong',
    slug: 'pong',
    description: 'The original arcade game. Bounce the ball past your opponent.',
    longDescription: 'The game that started it all. Control your paddle and bounce the ball past your opponent. Play vs AI or challenge a friend.',
    category: ['Arcade', 'Classic', 'Multiplayer'],
    difficulty: 'Variable',
    players: '1-2',
    thumbnail: '/images/pong.svg',
    featured: false,
    popular: false,
    isNew: false,
    tags: ['pong', 'arcade', 'classic', 'two-player', 'paddle'],
    controls: 'W/S Keys / Arrow Keys',
    color: '#a3e635',
    emoji: '🏓',
  },
  {
    id: '13',
    name: 'Whack-a-Mole',
    slug: 'whack-a-mole',
    description: 'Whack the moles as fast as you can before time runs out!',
    longDescription: 'Moles pop up from holes — hit them before they disappear! Score points for each hit. The game speeds up as time goes on. How high can you score?',
    category: ['Arcade', 'Casual', 'Skill'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/whackamole.svg',
    featured: false,
    popular: false,
    isNew: true,
    tags: ['whack-a-mole', 'arcade', 'casual', 'reflex', 'quick'],
    controls: 'Mouse / Touch',
    color: '#a855f7',
    emoji: '🔨',
  },
  {
    id: '14',
    name: 'Reaction Test',
    slug: 'reaction-test',
    description: 'Test your reflexes! Click as fast as you can when the screen changes.',
    longDescription: 'Wait for the screen to turn green, then click as fast as you can. Measure your reaction time in milliseconds. Track your best and average.',
    category: ['Skill', 'Casual'],
    difficulty: 'Easy',
    players: '1',
    thumbnail: '/images/reaction.svg',
    featured: false,
    popular: false,
    isNew: true,
    tags: ['reaction', 'reflex', 'speed', 'casual', 'test'],
    controls: 'Mouse / Touch / Space',
    color: '#14b8a6',
    emoji: '⚡',
  },
  {
    id: '15',
    name: 'Ludo',
    slug: 'ludo',
    description: 'Roll the dice and race your tokens home in this classic board game.',
    longDescription: 'Roll the dice and move your colored tokens around the board to get them all safely home before your opponents. Capture rivals and use safe zones strategically.',
    category: ['Board', 'Classic', 'Multiplayer'],
    difficulty: 'Easy',
    players: '2-4',
    thumbnail: '/images/ludo.svg',
    featured: true,
    popular: true,
    isNew: false,
    tags: ['ludo', 'board', 'dice', 'classic', 'multiplayer', 'family'],
    controls: 'Mouse / Touch',
    color: '#f43f5e',
    emoji: '🎲',
  },
  {
    id: '16',
    name: 'Tetris',
    slug: 'tetris',
    description: 'Stack falling tetrominoes and clear lines in the legendary puzzle game.',
    longDescription: 'Guide falling tetrominoes to fill complete rows and clear them. With 7 piece types, ghost piece preview, hold mechanic, and escalating speed, this is the definitive block puzzle challenge.',
    category: ['Arcade', 'Puzzle', 'Classic', 'Skill'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/tetris.svg',
    featured: true,
    popular: true,
    isNew: true,
    tags: ['tetris', 'blocks', 'puzzle', 'arcade', 'classic', 'lines'],
    controls: 'Arrow Keys / WASD / Touch',
    color: '#06b6d4',
    emoji: '🧱',
  },
  {
    id: '17',
    name: 'Word Search',
    slug: 'word-search',
    description: 'Find hidden words in a letter grid across all directions.',
    longDescription: 'Search for hidden words in a grid of letters. Words are hidden horizontally, vertically, and diagonally — even backwards! Choose from Animals, Countries, Sports, Food, and Science categories.',
    category: ['Puzzle', 'Casual', 'Classic'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/wordsearch.svg',
    featured: false,
    popular: true,
    isNew: true,
    tags: ['word', 'search', 'puzzle', 'letters', 'casual', 'brain'],
    controls: 'Mouse / Touch (drag to select)',
    color: '#8b5cf6',
    emoji: '🔤',
  },
  {
    id: '18',
    name: 'Typing Test',
    slug: 'typing-test',
    description: 'Test your typing speed and accuracy. How many WPM can you reach?',
    longDescription: 'Type the displayed text as fast and accurately as you can. Choose 15, 30, or 60 second modes. Track your WPM (words per minute), accuracy percentage, and personal best.',
    category: ['Skill', 'Casual'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/typing.svg',
    featured: false,
    popular: true,
    isNew: true,
    tags: ['typing', 'wpm', 'speed', 'accuracy', 'keyboard', 'skill'],
    controls: 'Keyboard',
    color: '#22c55e',
    emoji: '⌨️',
  },
  {
    id: '19',
    name: 'Solitaire',
    slug: 'solitaire',
    description: 'Classic Klondike card game — sort all cards to the foundation piles.',
    longDescription: 'The world\'s most played card game. Move cards between the 7 tableau columns using alternating colors, and build four foundation piles from Ace to King by suit. Features undo, auto-complete, and move counting.',
    category: ['Card', 'Classic', 'Strategy', 'Casual'],
    difficulty: 'Medium',
    players: '1',
    thumbnail: '/images/solitaire.svg',
    featured: true,
    popular: true,
    isNew: true,
    tags: ['solitaire', 'cards', 'klondike', 'classic', 'casual', 'patience'],
    controls: 'Mouse / Touch',
    color: '#10b981',
    emoji: '🃏',
  },
  {
    id: '20',
    name: 'Color Match',
    slug: 'color-match',
    description: 'Stroop Effect challenge — does the word match its ink color? Test your brain!',
    longDescription: 'A mind-bending Stroop Effect game. Your brain reads text faster than it processes color. Decide quickly whether the displayed word matches the color it is written in. Build combos and streaks for big points!',
    category: ['Puzzle', 'Skill', 'Casual'],
    difficulty: 'Variable',
    players: '1',
    thumbnail: '/images/colormatch.svg',
    featured: false,
    popular: true,
    isNew: true,
    tags: ['color', 'stroop', 'brain', 'reflex', 'casual', 'match'],
    controls: 'Mouse / Touch',
    color: '#a855f7',
    emoji: '🎨',
  },
];

export const categories = [
  { name: 'Arcade', emoji: '🕹️', color: '#f97316' },
  { name: 'Puzzle', emoji: '🧩', color: '#8b5cf6' },
  { name: 'Board', emoji: '♟️', color: '#0ea5e9' },
  { name: 'Classic', emoji: '⭐', color: '#f59e0b' },
  { name: 'Strategy', emoji: '🎯', color: '#22c55e' },
  { name: 'Multiplayer', emoji: '👥', color: '#ec4899' },
  { name: 'Casual', emoji: '😎', color: '#a3e635' },
  { name: 'Skill', emoji: '⚡', color: '#06b6d4' },
  { name: 'Card', emoji: '🃏', color: '#10b981' },
];

export function getGameBySlug(slug: string): Game | undefined {
  return games.find((g) => g.slug === slug);
}

export function getRelatedGames(game: Game, limit = 4): Game[] {
  return games
    .filter((g) => g.id !== game.id && g.category.some((c) => game.category.includes(c)))
    .slice(0, limit);
}

export function searchGames(query: string): Game[] {
  const q = query.toLowerCase();
  return games.filter(
    (g) =>
      g.name.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q) ||
      g.category.some((c) => c.toLowerCase().includes(q)) ||
      g.tags.some((t) => t.toLowerCase().includes(q))
  );
}

export function getGamesByCategory(category: string): Game[] {
  return games.filter((g) => g.category.includes(category));
}
